#!/usr/bin/env bash

do_shutdown() {
  sleep 3
  local _i
  curl "https://sctapi.ftqq.com/SCT313662TGZ7JRPbisBQfDZbabO1Kmmdt.send?title=训练完成&desp=Python脚本已执行完毕channel=9"
  for _i in 1 2 3 4 5 6 7 8 9; do
    /usr/bin/shutdown
    sleep 3
  done
  curl -fsS "https://sctapi.ftqq.com/SCT313662TGZ7JRPbisBQfDZbabO1Kmmdt.send?title=服务器关闭失败&desp=服务器关闭失败channel=9"
}
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"

export MMDIFF_RANDOM_SEED="${MMDIFF_RANDOM_SEED:-42}"
export MMDIFF_RUN_TIMESTAMP="${MMDIFF_RUN_TIMESTAMP:-$(date +%m%d-%H%M)}"

export MMDIFF_CLS_TOKEN_DIM="${MMDIFF_CLS_TOKEN_DIM:-192}"
export MMDIFF_CLS_HEAD_HIDDEN="${MMDIFF_CLS_HEAD_HIDDEN:-192}"
export MMDIFF_CLS_TRANSFORMER_LAYERS="${MMDIFF_CLS_TRANSFORMER_LAYERS:-1}"
export MMDIFF_CLS_TRANSFORMER_FF_DIM="${MMDIFF_CLS_TRANSFORMER_FF_DIM:-384}"

export MMDIFF_HSI_SE_RATIO="${MMDIFF_HSI_SE_RATIO:-8}"
export MMDIFF_HSI_RESIDUAL_BLOCKS="${MMDIFF_HSI_RESIDUAL_BLOCKS:-2}"
export MMDIFF_HSI_CONV_HIDDEN="${MMDIFF_HSI_CONV_HIDDEN:-64}"
export MMDIFF_HSI_AGG_MODE="${MMDIFF_HSI_AGG_MODE:-multi_token}"

export MMDIFF_LIDAR_HIDDEN="${MMDIFF_LIDAR_HIDDEN:-16}"
export MMDIFF_LIDAR_EXTRA_BLOCKS="${MMDIFF_LIDAR_EXTRA_BLOCKS:-0}"

export MMDIFF_RGB_STUDENT_CHECKPOINT="${MMDIFF_RGB_STUDENT_CHECKPOINT:-${RGB_STUDENT_CKPT:-}}"
export MMDIFF_FREEZE_RGB_STUDENT="${MMDIFF_FREEZE_RGB_STUDENT:-0}"

export MMDIFF_LOSS_WEIGHT_GLOBAL="${MMDIFF_LOSS_WEIGHT_GLOBAL:-0.25}"

export MMDIFF_MODALITY_COMBO="hsi+rgb+lidar"

# 4-axis 串行消融：α=3.5 固定；tau 可由外部环境覆盖；耦合残差在 multimodal 中默认开启。
export MMDIFF_CENTER_DISTANCE_BIAS_ALPHA=3.5
_bias_tau="${MMDIFF_CENTER_DISTANCE_BIAS_TAU:-2.0}"
export MMDIFF_CENTER_DISTANCE_BIAS_TAU="$_bias_tau"
_bias_tdot="${_bias_tau//./}"

# TB 目录名：prepare_tb_run_dir 使用 MMDIFF_EXPERIMENT_TAG；各块跑完 unset，避免串扰。

# 轴1a: global 2 + center 6
export MMDIFF_GLOBAL_QUERY_TOKENS=2
export MMDIFF_CENTER_QUERY_TOKENS=6
export MMDIFF_EXPERIMENT_TAG="a35_g2c6_t${_bias_tdot}"
python main.py
unset MMDIFF_GLOBAL_QUERY_TOKENS MMDIFF_CENTER_QUERY_TOKENS MMDIFF_EXPERIMENT_TAG

# 轴1b: global 6 + center 6
export MMDIFF_GLOBAL_QUERY_TOKENS=6
export MMDIFF_CENTER_QUERY_TOKENS=6
export MMDIFF_EXPERIMENT_TAG="a35_g6c6_t${_bias_tdot}"
python main.py
unset MMDIFF_GLOBAL_QUERY_TOKENS MMDIFF_CENTER_QUERY_TOKENS MMDIFF_EXPERIMENT_TAG

# 轴1c: global 3 + center 3
export MMDIFF_GLOBAL_QUERY_TOKENS=3
export MMDIFF_CENTER_QUERY_TOKENS=3
export MMDIFF_EXPERIMENT_TAG="a35_g3c3_t${_bias_tdot}"
python main.py
unset MMDIFF_GLOBAL_QUERY_TOKENS MMDIFF_CENTER_QUERY_TOKENS MMDIFF_EXPERIMENT_TAG

# 轴2: 耦合残差 MLP 更宽（MMDIFF_COUPLING_HIDDEN_FACTOR=2）
export MMDIFF_COUPLING_HIDDEN_FACTOR=2
export MMDIFF_EXPERIMENT_TAG="a35_chf2_t${_bias_tdot}"
python main.py
unset MMDIFF_COUPLING_HIDDEN_FACTOR MMDIFF_EXPERIMENT_TAG

# 轴3: classifier 多一层隐藏块
export MMDIFF_CLS_HEAD_LAYERS=3
export MMDIFF_EXPERIMENT_TAG="a35_hl3_t${_bias_tdot}"
python main.py
unset MMDIFF_CLS_HEAD_LAYERS MMDIFF_EXPERIMENT_TAG

# 轴4a: global 行 anticenter bias
export MMDIFF_GLOBAL_ANTICENTER_BIAS=1.0
export MMDIFF_EXPERIMENT_TAG="a35_ac10_t${_bias_tdot}"
python main.py
unset MMDIFF_GLOBAL_ANTICENTER_BIAS MMDIFF_EXPERIMENT_TAG

# 轴4b
export MMDIFF_GLOBAL_ANTICENTER_BIAS=2.0
export MMDIFF_EXPERIMENT_TAG="a35_ac20_t${_bias_tdot}"
python main.py
unset MMDIFF_GLOBAL_ANTICENTER_BIAS MMDIFF_EXPERIMENT_TAG

do_shutdown
